---
title: "Exploratory Data Analysis Peer Assessment 2"
author: "Alex Konkel"
date: "December 22, 2015"
output: html_document
---

This markdown document will run all the analyses and produce the graphs asked for in the 2nd peer assessment in the John Hopkins Exploratory Data Analysis Coursera class.  The course asks you to copy the relevant code directly into a browser, which seems pretty silly for a data science series that also includes work on reproducible research and sharing data/analyses.  

## Loading the Data
First we need to download the data, unzip it, and load it.
``` {r}
fileName <- c("pm_data.zip")
if(!file.exists(fileName)) {
  download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2FNEI_data.zip", fileName)
  message("... Unzipping archived source data ...")
  unzip(fileName)
} else {
  message("... Source file already exists ...")
}
pm_data <- readRDS('summarySCC_PM25.rds')
pm_class <- readRDS('Source_Classification_Code.rds')
```
The data seems to load in with reasonable data classes, so we're good to go.

## Question 1: Have Emissions Decreased?
The first part of the assignment is to determine if total emissions from PM2.5 have decreased from 1999 to 2008.  As part of answering the question, we need to make a base graphics plot, saved as a PNG, that shows total emissions for 1999, 2002, 2005, and 2008.  

